In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
pd.DataFrame({'A': [1, 2, 3],'B':[4, 5, 6]})

A  B
0  1  4
1  2  5
2  3  6

In [9]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [10]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [15]:
dates = pd.date_range("20230101", periods=6)
dates

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06'],
              dtype='datetime64[ns]', freq='D')

In [16]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

A         B         C         D
2023-01-01  0.367499  0.460834 -0.677562 -0.547760
2023-01-02  0.142564  2.269747 -0.371492 -0.922889
2023-01-03  0.818588  1.710490 -1.809343  0.658250
2023-01-04  1.865549 -0.560709  0.153803 -2.473157
2023-01-05 -0.237241  0.512410  1.851669  1.086962
2023-01-06  0.500247  0.648036  0.326539  0.321646

In [18]:
df.head(2)

A         B         C         D
2023-01-01  0.367499  0.460834 -0.677562 -0.547760
2023-01-02  0.142564  2.269747 -0.371492 -0.922889

In [19]:
df.sample(2)

A         B         C         D
2023-01-05 -0.237241  0.512410  1.851669  1.086962
2023-01-01  0.367499  0.460834 -0.677562 -0.547760

In [29]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.date_range("20230102", periods=4),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)

df2

A          B    C  D      E    F
0  1.0 2023-01-02  1.0  3   test  foo
1  1.0 2023-01-03  1.0  3  train  foo
2  1.0 2023-01-04  1.0  3   test  foo
3  1.0 2023-01-05  1.0  3  train  foo

In [31]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [34]:
df2.all

<bound method NDFrame._add_numeric_operations.<locals>.all of      A          B    C  D      E    F
0  1.0 2023-01-02  1.0  3   test  foo
1  1.0 2023-01-03  1.0  3  train  foo
2  1.0 2023-01-04  1.0  3   test  foo
3  1.0 2023-01-05  1.0  3  train  foo>

In [35]:
df2.add

<bound method flex_arith_method_FRAME.<locals>.f of      A          B    C  D      E    F
0  1.0 2023-01-02  1.0  3   test  foo
1  1.0 2023-01-03  1.0  3  train  foo
2  1.0 2023-01-04  1.0  3   test  foo
3  1.0 2023-01-05  1.0  3  train  foo>

In [36]:
df2.tail()

A          B    C  D      E    F
0  1.0 2023-01-02  1.0  3   test  foo
1  1.0 2023-01-03  1.0  3  train  foo
2  1.0 2023-01-04  1.0  3   test  foo
3  1.0 2023-01-05  1.0  3  train  foo

In [39]:
df.index

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06'],
              dtype='datetime64[ns]', freq='D')

In [40]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [43]:
a= df.to_numpy()
a

array([[ 0.36749944,  0.46083419, -0.677562  , -0.54776041],
       [ 0.14256391,  2.26974679, -0.37149207, -0.92288883],
       [ 0.81858767,  1.71048986, -1.8093431 ,  0.65825007],
       [ 1.86554859, -0.56070923,  0.1538027 , -2.47315682],
       [-0.23724078,  0.51240966,  1.85166926,  1.08696248],
       [ 0.50024713,  0.6480363 ,  0.32653865,  0.32164587]])

In [42]:
df

A         B         C         D
2023-01-01  0.367499  0.460834 -0.677562 -0.547760
2023-01-02  0.142564  2.269747 -0.371492 -0.922889
2023-01-03  0.818588  1.710490 -1.809343  0.658250
2023-01-04  1.865549 -0.560709  0.153803 -2.473157
2023-01-05 -0.237241  0.512410  1.851669  1.086962
2023-01-06  0.500247  0.648036  0.326539  0.321646

In [44]:
a # Once you convert it to a numpy array,you can perform all functionalities of it

array([[ 0.36749944,  0.46083419, -0.677562  , -0.54776041],
       [ 0.14256391,  2.26974679, -0.37149207, -0.92288883],
       [ 0.81858767,  1.71048986, -1.8093431 ,  0.65825007],
       [ 1.86554859, -0.56070923,  0.1538027 , -2.47315682],
       [-0.23724078,  0.51240966,  1.85166926,  1.08696248],
       [ 0.50024713,  0.6480363 ,  0.32653865,  0.32164587]])

In [45]:
a.mean()

0.2539449728041385

In [46]:
a.max()

2.2697467905836675

In [50]:
np.corrcoef(a)

array([[ 1.        ,  0.78711302,  0.77470136,  0.49072014, -0.87333581,
         0.94054623],
       [ 0.78711302,  1.        ,  0.58207488,  0.19965267, -0.39405355,
         0.94884015],
       [ 0.77470136,  0.58207488,  1.        , -0.12162881, -0.76432616,
         0.73420686],
       [ 0.49072014,  0.19965267, -0.12162881,  1.        , -0.48643764,
         0.33239177],
       [-0.87333581, -0.39405355, -0.76432616, -0.48643764,  1.        ,
        -0.66408625],
       [ 0.94054623,  0.94884015,  0.73420686,  0.33239177, -0.66408625,
         1.        ]])

In [51]:
np.cov(a)

array([[ 0.35571857,  0.65551712,  0.6970742 ,  0.52566429, -0.46070167,
         0.08777906],
       [ 0.65551712,  1.94978778,  1.22620747,  0.50071444, -0.48666955,
         0.20732144],
       [ 0.6970742 ,  1.22620747,  2.27605554, -0.32957117, -1.01989486,
         0.17332746],
       [ 0.52566429,  0.50071444, -0.32957117,  3.22583875, -0.77274064,
         0.09341768],
       [-0.46070167, -0.48666955, -1.01989486, -0.77274064,  0.78229491,
        -0.09191095],
       [ 0.08777906,  0.20732144,  0.17332746,  0.09341768, -0.09191095,
         0.02448584]])

In [53]:
b=df2.to_numpy()
b

array([[1.0, Timestamp('2023-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2023-01-03 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2023-01-04 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2023-01-05 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [55]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.576201  0.840135 -0.087731 -0.312825
std    0.723909  1.005171  1.215204  1.296098
min   -0.237241 -0.560709 -1.809343 -2.473157
25%    0.198798  0.473728 -0.601045 -0.829107
50%    0.433873  0.580223 -0.108845 -0.113057
75%    0.739003  1.444876  0.283355  0.574099
max    1.865549  2.269747  1.851669  1.086962

In [56]:
df

A         B         C         D
2023-01-01  0.367499  0.460834 -0.677562 -0.547760
2023-01-02  0.142564  2.269747 -0.371492 -0.922889
2023-01-03  0.818588  1.710490 -1.809343  0.658250
2023-01-04  1.865549 -0.560709  0.153803 -2.473157
2023-01-05 -0.237241  0.512410  1.851669  1.086962
2023-01-06  0.500247  0.648036  0.326539  0.321646

In [57]:
df.T

2023-01-01  2023-01-02  2023-01-03  2023-01-04  2023-01-05  2023-01-06
A    0.367499    0.142564    0.818588    1.865549   -0.237241    0.500247
B    0.460834    2.269747    1.710490   -0.560709    0.512410    0.648036
C   -0.677562   -0.371492   -1.809343    0.153803    1.851669    0.326539
D   -0.547760   -0.922889    0.658250   -2.473157    1.086962    0.321646

In [58]:
df.sort_index()

A         B         C         D
2023-01-01  0.367499  0.460834 -0.677562 -0.547760
2023-01-02  0.142564  2.269747 -0.371492 -0.922889
2023-01-03  0.818588  1.710490 -1.809343  0.658250
2023-01-04  1.865549 -0.560709  0.153803 -2.473157
2023-01-05 -0.237241  0.512410  1.851669  1.086962
2023-01-06  0.500247  0.648036  0.326539  0.321646

In [59]:
df.sort_values(by="B")

A         B         C         D
2023-01-04  1.865549 -0.560709  0.153803 -2.473157
2023-01-01  0.367499  0.460834 -0.677562 -0.547760
2023-01-05 -0.237241  0.512410  1.851669  1.086962
2023-01-06  0.500247  0.648036  0.326539  0.321646
2023-01-03  0.818588  1.710490 -1.809343  0.658250
2023-01-02  0.142564  2.269747 -0.371492 -0.922889

In [61]:
df["A"]

2023-01-01    0.367499
2023-01-02    0.142564
2023-01-03    0.818588
2023-01-04    1.865549
2023-01-05   -0.237241
2023-01-06    0.500247
Freq: D, Name: A, dtype: float64

In [62]:
df[0:3]

A         B         C         D
2023-01-01  0.367499  0.460834 -0.677562 -0.547760
2023-01-02  0.142564  2.269747 -0.371492 -0.922889
2023-01-03  0.818588  1.710490 -1.809343  0.658250

In [65]:
df["20230101":"20230103"]

A         B         C         D
2023-01-01  0.367499  0.460834 -0.677562 -0.547760
2023-01-02  0.142564  2.269747 -0.371492 -0.922889
2023-01-03  0.818588  1.710490 -1.809343  0.658250

In [67]:
df.loc[dates[1]]

A    0.142564
B    2.269747
C   -0.371492
D   -0.922889
Name: 2023-01-02 00:00:00, dtype: float64

In [68]:
df.loc[:,["A","B"]]

A         B
2023-01-01  0.367499  0.460834
2023-01-02  0.142564  2.269747
2023-01-03  0.818588  1.710490
2023-01-04  1.865549 -0.560709
2023-01-05 -0.237241  0.512410
2023-01-06  0.500247  0.648036

In [80]:
df.loc["20230101":"20230104","A":"D"]

A         B         C         D
2023-01-01  0.367499  0.460834 -0.677562 -0.547760
2023-01-02  0.142564  2.269747 -0.371492 -0.922889
2023-01-03  0.818588  1.710490 -1.809343  0.658250
2023-01-04  1.865549 -0.560709  0.153803 -2.473157

In [74]:
df.loc[dates[0],"A"]

0.3674994411265685

In [78]:
df.at[dates[0],"A"] # It returns a scaler

0.3674994411265685

In [79]:
df.iloc[3]

A    1.865549
B   -0.560709
C    0.153803
D   -2.473157
Name: 2023-01-04 00:00:00, dtype: float64

In [83]:
df.iloc[3:5,0:2]

A         B
2023-01-04  1.865549 -0.560709
2023-01-05 -0.237241  0.512410

In [84]:
df.iloc[[1, 2, 4], [0, 2]]

A         C
2023-01-02  0.142564 -0.371492
2023-01-03  0.818588 -1.809343
2023-01-05 -0.237241  1.851669

In [85]:
df.iloc[1:3, :] #For slicing rows explicitly:

A         B         C         D
2023-01-02  0.142564  2.269747 -0.371492 -0.922889
2023-01-03  0.818588  1.710490 -1.809343  0.658250

In [86]:
df.iloc[:, 1:3] #For slicing columns explicitly:

B         C
2023-01-01  0.460834 -0.677562
2023-01-02  2.269747 -0.371492
2023-01-03  1.710490 -1.809343
2023-01-04 -0.560709  0.153803
2023-01-05  0.512410  1.851669
2023-01-06  0.648036  0.326539

In [87]:
df.iloc[1, 1] #For getting a value explicitly:

2.2697467905836675

In [88]:
df.iat[1, 1] #For getting fast access to a scalar (equivalent to the prior method):

2.2697467905836675

In [91]:
df[df["C"] > 0]

A         B         C         D
2023-01-04  1.865549 -0.560709  0.153803 -2.473157
2023-01-05 -0.237241  0.512410  1.851669  1.086962
2023-01-06  0.500247  0.648036  0.326539  0.321646

In [92]:
df[df > 0]

A         B         C         D
2023-01-01  0.367499  0.460834       NaN       NaN
2023-01-02  0.142564  2.269747       NaN       NaN
2023-01-03  0.818588  1.710490       NaN  0.658250
2023-01-04  1.865549       NaN  0.153803       NaN
2023-01-05       NaN  0.512410  1.851669  1.086962
2023-01-06  0.500247  0.648036  0.326539  0.321646

In [94]:
df2 = df.copy()
df2

A         B         C         D
2023-01-01  0.367499  0.460834 -0.677562 -0.547760
2023-01-02  0.142564  2.269747 -0.371492 -0.922889
2023-01-03  0.818588  1.710490 -1.809343  0.658250
2023-01-04  1.865549 -0.560709  0.153803 -2.473157
2023-01-05 -0.237241  0.512410  1.851669  1.086962
2023-01-06  0.500247  0.648036  0.326539  0.321646

In [97]:
df2["E"] = ["one", "one", "two", "three", "four", "three"]
df2

A         B         C         D      E
2023-01-01  0.367499  0.460834 -0.677562 -0.547760    one
2023-01-02  0.142564  2.269747 -0.371492 -0.922889    one
2023-01-03  0.818588  1.710490 -1.809343  0.658250    two
2023-01-04  1.865549 -0.560709  0.153803 -2.473157  three
2023-01-05 -0.237241  0.512410  1.851669  1.086962   four
2023-01-06  0.500247  0.648036  0.326539  0.321646  three

In [96]:
df2[df2["E"].isin(["two", "four"])]

A        B         C         D     E
2023-01-03  0.818588  1.71049 -1.809343  0.658250   two
2023-01-05 -0.237241  0.51241  1.851669  1.086962  four

In [98]:
df.at[dates[0], "A"] = 0  #Setting values by label:

In [99]:
#Setting values by position:
df.iat[0, 1] = 0

In [100]:
df

A         B         C         D
2023-01-01  0.000000  0.000000 -0.677562 -0.547760
2023-01-02  0.142564  2.269747 -0.371492 -0.922889
2023-01-03  0.818588  1.710490 -1.809343  0.658250
2023-01-04  1.865549 -0.560709  0.153803 -2.473157
2023-01-05 -0.237241  0.512410  1.851669  1.086962
2023-01-06  0.500247  0.648036  0.326539  0.321646

In [102]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])
df1.loc[dates[0] : dates[1], "E"] = 1
df1

A         B         C         D    E
2023-01-01  0.000000  0.000000 -0.677562 -0.547760  1.0
2023-01-02  0.142564  2.269747 -0.371492 -0.922889  1.0
2023-01-03  0.818588  1.710490 -1.809343  0.658250  NaN
2023-01-04  1.865549 -0.560709  0.153803 -2.473157  NaN

In [103]:
df1.dropna(how="any")

A         B         C         D    E
2023-01-01  0.000000  0.000000 -0.677562 -0.547760  1.0
2023-01-02  0.142564  2.269747 -0.371492 -0.922889  1.0

In [104]:
df1.fillna(value=5)

A         B         C         D    E
2023-01-01  0.000000  0.000000 -0.677562 -0.547760  1.0
2023-01-02  0.142564  2.269747 -0.371492 -0.922889  1.0
2023-01-03  0.818588  1.710490 -1.809343  0.658250  5.0
2023-01-04  1.865549 -0.560709  0.153803 -2.473157  5.0

In [105]:
pd.isna(df1)

A      B      C      D      E
2023-01-01  False  False  False  False  False
2023-01-02  False  False  False  False  False
2023-01-03  False  False  False  False   True
2023-01-04  False  False  False  False   True

In [106]:
df

A         B         C         D
2023-01-01  0.000000  0.000000 -0.677562 -0.547760
2023-01-02  0.142564  2.269747 -0.371492 -0.922889
2023-01-03  0.818588  1.710490 -1.809343  0.658250
2023-01-04  1.865549 -0.560709  0.153803 -2.473157
2023-01-05 -0.237241  0.512410  1.851669  1.086962
2023-01-06  0.500247  0.648036  0.326539  0.321646

In [107]:
df.mean()

A    0.514951
B    0.763329
C   -0.087731
D   -0.312825
dtype: float64

In [108]:
df.mean(axis=1)

2023-01-01   -0.306331
2023-01-02    0.279482
2023-01-03    0.344496
2023-01-04   -0.253629
2023-01-05    0.803450
2023-01-06    0.449117
Freq: D, dtype: float64

In [109]:
s = pd.Series([1, 3, 5, np.nan, 6, 8], index=dates).shift(2)
s

2023-01-01    NaN
2023-01-02    NaN
2023-01-03    1.0
2023-01-04    3.0
2023-01-05    5.0
2023-01-06    NaN
Freq: D, dtype: float64

In [110]:
df.sub(s, axis="index")

A         B         C         D
2023-01-01       NaN       NaN       NaN       NaN
2023-01-02       NaN       NaN       NaN       NaN
2023-01-03 -0.181412  0.710490 -2.809343 -0.341750
2023-01-04 -1.134451 -3.560709 -2.846197 -5.473157
2023-01-05 -5.237241 -4.487590 -3.148331 -3.913038
2023-01-06       NaN       NaN       NaN       NaN

In [111]:
df

A         B         C         D
2023-01-01  0.000000  0.000000 -0.677562 -0.547760
2023-01-02  0.142564  2.269747 -0.371492 -0.922889
2023-01-03  0.818588  1.710490 -1.809343  0.658250
2023-01-04  1.865549 -0.560709  0.153803 -2.473157
2023-01-05 -0.237241  0.512410  1.851669  1.086962
2023-01-06  0.500247  0.648036  0.326539  0.321646

In [112]:
df.agg(lambda x: np.mean(x) * 5.6)

A    2.883726
B    4.274642
C   -0.491294
D   -1.751818
dtype: float64

In [113]:
df.transform(lambda x: x * 101.2)

A           B           C           D
2023-01-01    0.000000    0.000000  -68.569274  -55.433353
2023-01-02   14.427468  229.698375  -37.594997  -93.396349
2023-01-03   82.841072  173.101574 -183.105522   66.614907
2023-01-04  188.793517  -56.743774   15.564834 -250.283470
2023-01-05  -24.008767   51.855858  187.388929  110.000603
2023-01-06   50.625010   65.581274   33.045711   32.550562

In [117]:
s = pd.Series(np.random.randint(0, 7, size=10))
s

0    0
1    3
2    0
3    3
4    1
5    4
6    0
7    3
8    0
9    1
dtype: int32

In [118]:
s.value_counts()

0    4
3    3
1    2
4    1
Name: count, dtype: int64

In [120]:
s = pd.Series(["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"])

In [121]:
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

In [122]:
s.str.upper()

0       A
1       B
2       C
3    AABA
4    BACA
5     NaN
6    CABA
7     DOG
8     CAT
dtype: object

In [123]:
df = pd.DataFrame(np.random.randn(10, 4))
df

0         1         2         3
0 -1.181670  0.862110 -0.347288  0.204457
1 -1.335663  0.685073  0.663499  1.337165
2  0.555950  0.446597 -1.766106 -0.762744
3 -1.663506  0.356902 -0.499622 -0.238223
4 -0.200312  0.378812  0.205369 -1.446889
5  2.037204 -0.088155  0.439030  0.133626
6 -0.671602  0.663133 -0.969837  1.029286
7  1.583871  0.439203  0.708662 -0.405257
8 -0.273606 -0.082758  0.229333  1.089141
9  0.559796 -1.713731 -0.301177 -0.975106

In [124]:
pieces=[df[:3],df[3:7],df[7:]]

In [125]:
pd.concat(pieces)

0         1         2         3
0 -1.181670  0.862110 -0.347288  0.204457
1 -1.335663  0.685073  0.663499  1.337165
2  0.555950  0.446597 -1.766106 -0.762744
3 -1.663506  0.356902 -0.499622 -0.238223
4 -0.200312  0.378812  0.205369 -1.446889
5  2.037204 -0.088155  0.439030  0.133626
6 -0.671602  0.663133 -0.969837  1.029286
7  1.583871  0.439203  0.708662 -0.405257
8 -0.273606 -0.082758  0.229333  1.089141
9  0.559796 -1.713731 -0.301177 -0.975106

In [127]:
df = pd.DataFrame(
    {
        "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
        "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
        "C": np.random.randn(8),
        "D": np.random.randn(8),
    }
)
df

A      B         C         D
0  foo    one  1.222585 -0.253565
1  bar    one  0.372344 -0.429793
2  foo    two -0.092883  0.405135
3  bar  three  0.949962  1.919492
4  foo    two  0.619769 -0.726960
5  bar    two  0.993621  1.158223
6  foo    one -0.917123 -0.209409
7  foo  three -1.035055 -1.615092

In [130]:
df.groupby("A")[["C", "D"]].sum()

C         D
A                      
bar  2.315928  2.647921
foo -0.202707 -2.399891

In [131]:
df.groupby(["A", "B"]).sum()

C         D
A   B                        
bar one    0.372344 -0.429793
    three  0.949962  1.919492
    two    0.993621  1.158223
foo one    0.305462 -0.462974
    three -1.035055 -1.615092
    two    0.526886 -0.321825

In [132]:
 df3 = pd.DataFrame(np.random.randint(0, 5, (10, 5)))

In [133]:
df3.to_csv("trial.csv")

In [136]:
df=pd.read_csv("trial.csv")

In [137]:
df

Unnamed: 0  0  1  2  3  4
0           0  1  1  4  1  4
1           1  4  2  1  0  0
2           2  4  4  0  1  1
3           3  2  2  1  3  4
4           4  3  1  4  2  4
5           5  0  0  0  0  1
6           6  1  1  3  4  1
7           7  1  4  2  1  1
8           8  4  3  4  4  4
9           9  0  0  1  1  2

In [163]:
df=pd.DataFrame(np.random.randint(0, 5, (10, 5)), columns=list('ABCDE'))
df

A  B  C  D  E
0  0  2  1  2  1
1  4  2  2  1  1
2  2  0  4  3  2
3  4  2  4  4  2
4  2  3  2  2  3
5  4  0  1  1  1
6  3  1  1  2  0
7  4  2  1  1  4
8  1  4  3  4  3
9  1  3  2  3  4

In [ ]:
# How to change the name of columns? How to add names to the columns?